[workspace]
members = [
    "phlow-engine",
    "phlow",
    "sdk",
    "modules/http_rest_api",
    "modules/echo",
    "modules/amqp",
    "modules/log",
    "modules/sleep",
]
resolver = "2"

[workspace.dependencies]
phlow-engine = { path = "phlow-engine" }
sdk = { path = "sdk" }
valu3 = "0.8"
tokio = { version = "1.44.1", features = ["full", "tracing"] }
serde = { version = "1.0", features = ["derive"] }
crossbeam = "0.8"

# OpenTelemetry
opentelemetry = "0.29.1"
opentelemetry_sdk = "=0.29.0"
opentelemetry-prometheus = "=0.29.0"
tracing-opentelemetry = "=0.30.0"
opentelemetry-stdout = "=0.29.0"
opentelemetry-semantic-conventions = { version = "=0.29.0", features = [
    "semconv_experimental",
] }
tracing-core = "=0.1.33"
opentelemetry-otlp = { version = "=0.29.0", features = ["grpc-tonic"] }
tracing-subscriber = "=0.3.19"
tracing = "=0.1.41"

#phlow
libloading = "0.8"
clap = "4.5.35"
serde_yaml = "0.9"
serde_json = "1.0"
toml = "0.8"
regex = "1.11.1"
futures = "0.3"
mimalloc = { version = "0.1", features = ["secure"] }
libc = "0.2"

#Engine
rhai = { version = "1.21.0", features = ["serde", "sync"] }
