version: "3.9"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - 4317:4317
      - 4318:4318
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # Se quiser persistir dados de dashboards etc.
    volumes:
      - grafana_data:/var/lib/grafana
      # Aqui montamos a pasta provisioning, incluindo o datasource.yml
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3100:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector.yml:/etc/otel-collector-config.yml
    command: [ "--config=/etc/otel-collector-config.yml" ]
    ports:
      - "4318:4318" # OTLP HTTP
      - "4317:4317" # OTLP gRPC
      - "9464:9464" # Prometheus scrape
    networks:
      - monitoring

networks:
  monitoring:


volumes:
  grafana_data:
