[package]
name = "phlow-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
rhai = { workspace = true }
regex = { workspace = true }
valu3 = { workspace = true }
tokio = { workspace = true }
sdk = { workspace = true }
crossbeam = { workspace = true }
