[package]
name = "phlow"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { path = "../sdk" }
phlow-engine = { path = "../phlow-engine" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
libloading = "0.8"
clap = "4"
serde_yaml = "0.9"
serde_json = "1.0"
toml = "0.8"
regex = "1.11.1"
crossbeam = "0.8"
futures = "0.3"

# OpenTelemetry
opentelemetry = "0.29.0"
opentelemetry_sdk = "0.29.0"
opentelemetry-jaeger = "0.22.0" # Exportador de traces para Jaeger
opentelemetry-prometheus = "0.29.0" # Exportador de métricas para Prometheus
tracing-opentelemetry = "0.30.0"
opentelemetry-stdout = "0.29.0"
opentelemetry-semantic-conventions = { version = "0.29.0", features = [
    "semconv_experimental",
] }
tracing-core = "0.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
tracing-subscriber = "0.3"
tracing = "0.1"
