[package]
name = "phlow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sdk = { path = "../sdk" }
tokio = { version = "1", features = ["full"] }
libloading = "0.8"
phlow-engine = { path = "../phlow-engine" }
clap = "4"
serde_yaml = "0.9"
serde_json = "1.0"
toml = "0.8"
regex = "1.11.1"


# OpenTelemetry
opentelemetry = "0.29.0"
opentelemetry_sdk = "0.29.0"
opentelemetry-jaeger = "0.22.0"
opentelemetry-prometheus = "0.29.0"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = "0.3.19"
opentelemetry-stdout = "0.29.0"
opentelemetry-semantic-conventions = { version = "0.29.0", features = [
    "semconv_experimental",
] }
tracing-core = "0.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
