main = "http_rest_api"

[[modules]]
name = "http_rest_api"

[[modules]]
name = "echo"

[[steps]]
id = "echo"
module = "echo"

[steps.input]
message = "Hello, World!"

[[steps]]

[steps.return]
status_code = 201
body = "{{steps.echo}}"

[steps.return.headers]
Content-Type = "application/json"
